---
title: "10768 - Bases da Matemática e Estatística - Bict Mar - Unifesp"
subtitle: "Cronograma: 1º semestre de 2026"
tbl-colwidths: [2,1,2,5,5,3,3]
---

[📄 Calendário Acadêmico 2026 Unifesp (PDF)](course-info/academic-calendar-2026.pdf){target="_blank"}

::: {.column-screen-inset-right .cronograma-bme}

| Aula | Data | Dia da semana | Turma A | Turma B | Material<br>teórico | Lab.<br>Informática |
|---|---|---|---|---|---|---|
|  | 03/03 | Terça-feira | [*Semana de recepção de calouros*]{.aula-celula .is-teoria} |  |  |  |
|  | 05/03 | Quinta-feira | [*Semana de recepção de calouros*]{.aula-celula .is-teoria} |  |  |  |
| [1]{.aula-idx .dia-mesma-atividade} | 10/03 | Terça-feira | [Introdução da UC: Matemática e Estatística; Dados e Modelos]{.aula-celula .is-teoria} | [Introdução da UC: Matemática e Estatística; Dados e Modelos]{.aula-celula .is-teoria} |  |  |
| [2]{.aula-idx .dia-mesma-atividade} | 12/03 | Quinta-feira | [A geometria e a álgebra de vetores]{.aula-celula .is-teoria} | [A geometria e a álgebra de vetores]{.aula-celula .is-teoria} | [A geometria e a álgebra de vetores](content/slides/slides-bme-geometria-vetores.html){target="_blank"} |  |
| [3]{.aula-idx .dia-mesma-atividade} | 17/03 | Terça-feira | [Comprimento e ângulo: o produto escalar]{.aula-celula .is-teoria} | [Comprimento e ângulo: o produto escalar]{.aula-celula .is-teoria} | [Comprimento e ângulo: o produto escalar](content/slides/slides-bme-comprimento-angulo.html){target="_blank"} |  |
| [4]{.aula-idx .dia-revezamento} | 19/03 | Quinta-feira | [Sistemas de Equações Lineares: método de eliminação de Gauss e Gauss-Jordan]{.aula-celula .is-teoria} | [LAB. INFO: Álgebra de vetores, comprimento e ângulo em planilha eletrônica]{.aula-celula .is-pratica} | [Sistemas de Equações Lineares](content/slides/slides-bme-sistema-equacoes-lineares.html){target="_blank"} |  |
| [5]{.aula-idx .dia-revezamento} | 24/03 | Terça-feira | [LAB. INFO: Álgebra de vetores, comprimento e ângulo em planilha eletrônica]{.aula-celula .is-pratica} | [Sistemas de Equações Lineares: método de eliminação de Gauss e Gauss-Jordan]{.aula-celula .is-teoria} | [Sistemas de Equações Lineares](content/slides/slides-bme-sistema-equacoes-lineares.html){target="_blank"} |  |
| [6]{.aula-idx .dia-revezamento} | 26/03 | Quinta-feira | [Sistemas de Equações Lineares: método de eliminação de Gauss e Gauss-Jordan]{.aula-celula .is-teoria} | [LAB. INFO: Lista 2: produto escalar]{.aula-celula .is-pratica} | [Sistemas de Equações Lineares](content/slides/slides-bme-sistema-equacoes-lineares.html){target="_blank"} |  |
| [7]{.aula-idx .dia-revezamento} | 31/03 | Terça-feira | [LAB. INFO: Lista 2: produto escalar]{.aula-celula .is-pratica} | [Sistemas de Equações Lineares: método de eliminação de Gauss e Gauss-Jordan]{.aula-celula .is-teoria} | [Sistemas de Equações Lineares](content/slides/slides-bme-sistema-equacoes-lineares.html){target="_blank"} |  |
| [8]{.aula-idx .dia-mesma-atividade} | 02/04 | Quinta-feira | [Álgebra de Matrizes]{.aula-celula .is-teoria} | [Álgebra de Matrizes]{.aula-celula .is-teoria} | [Matrizes](https://fcopf.github.io/mead/content/multivariada-numerica/intro-matrizes.html){target="_blank"}<br>[Matriz de Leslie](content/slides/slides-bme-matriz-leslie.html){target="_blank"} |  |
| [9]{.aula-idx .dia-revezamento} | 07/04 | Terça-feira | [A inversa de uma matriz]{.aula-celula .is-teoria} | [LAB. INFO: Álgebra de matrizes em planilha eletrônica]{.aula-celula .is-pratica} | [Matrizes](https://fcopf.github.io/mead/content/multivariada-numerica/intro-matrizes.html){target="_blank"} | [Similaridade por cosseno - Planilha eletrônica](https://fcopf.github.io/mead/content/multivariada-numerica/cossine-similarity.html){target="_blank"} |
| [10]{.aula-idx .dia-revezamento} | 09/04 | Quinta-feira | [LAB. INFO: Álgebra de matrizes em planilha eletrônica]{.aula-celula .is-pratica} | [A inversa de uma matriz]{.aula-celula .is-teoria} | [Matrizes](https://fcopf.github.io/mead/content/multivariada-numerica/intro-matrizes.html){target="_blank"} | [Similaridade por cosseno - Planilha eletrônica](https://fcopf.github.io/mead/content/multivariada-numerica/cossine-similarity.html){target="_blank"} |
| [11]{.aula-idx .dia-mesma-atividade} | 14/04 | Terça-feira | [**Prova 1**]{.aula-celula .is-teoria} | [**Prova 1**]{.aula-celula .is-teoria} |  |  |
| [12]{.aula-idx .dia-mesma-atividade} | 16/04 | Quinta-feira | [Método dos Mínimos Quadrados   regressão linear simples (representação vetorial)]{.aula-celula .is-teoria} | [Método dos Mínimos Quadrados   regressão linear simples (representação vetorial)]{.aula-celula .is-teoria} | [Regressão linear simples e Método dos Mínimos Quadrados](https://fcopf.github.io/mead/content/regressao-linear/metodo-minimos-quadrados-apresentacao.html){target="_blank"} |  |
|  | 21/04 | Terça-feira | [*Feriado (Tiradentes)*]{.aula-celula .is-teoria} |  |  |  |
| [13]{.aula-idx .dia-revezamento} | 23/04 | Quinta-feira | [Método dos Mínimos Quadrados   regressão linear simples (representação vetorial)]{.aula-celula .is-teoria} | [LAB. INFO: Regressão Linear Simples pelo Método dos Mínimos Quadrados em planilha eletrônica (representação vetorial)]{.aula-celula .is-pratica} | [Regressão linear simples e Método dos Mínimos Quadrados](https://fcopf.github.io/mead/content/regressao-linear/metodo-minimos-quadrados-apresentacao.html){target="_blank"} |  |
| [14]{.aula-idx .dia-revezamento} | 28/04 | Terça-feira | [LAB. INFO: Regressão Linear Simples pelo Método dos Mínimos Quadrados em planilha eletrônica (representação vetorial)]{.aula-celula .is-pratica} | [Método dos Mínimos Quadrados   regressão linear simples (representação vetorial)]{.aula-celula .is-teoria} | [Regressão linear simples e Método dos Mínimos Quadrados](https://fcopf.github.io/mead/content/regressao-linear/metodo-minimos-quadrados-apresentacao.html){target="_blank"} |  |
| [15]{.aula-idx .dia-mesma-atividade} | 30/04 | Quinta-feira | [Medidas de tendência central e de variação]{.aula-celula .is-teoria} | [Medidas de tendência central e de variação]{.aula-celula .is-teoria} | [Medidas de tendência central](https://fcopf.github.io/mead/content/estatistica-descritiva/tendcentral.html){target="_blank"}<br>[Medidas de variação](https://fcopf.github.io/mead/content/estatistica-descritiva/variacao.html){target="_blank"} |  |
| [16]{.aula-idx .dia-mesma-atividade} | 05/05 | Terça-feira | [Covariância e coeficiente de correlação]{.aula-celula .is-teoria} | [Covariância e coeficiente de correlação]{.aula-celula .is-teoria} | [Associação entre duas variáveis quantitativas](https://fcopf.github.io/mead/content/medidas-associacao/biquanti.html){target="_blank"} |  |
| [17]{.aula-idx .dia-mesma-atividade} | 07/05 | Quinta-feira | [Partição da soma dos quadrados e coeficiente de determinação na regressão linear]{.aula-celula .is-teoria} | [Partição da soma dos quadrados e coeficiente de determinação na regressão linear]{.aula-celula .is-teoria} |  |  |
| [18]{.aula-idx .dia-mesma-atividade} | 12/05 | Terça-feira | [**Prova 2**]{.aula-celula .is-teoria} | [**Prova 2**]{.aula-celula .is-teoria} |  |  |
| [19]{.aula-idx .dia-mesma-atividade} | 14/05 | Quinta-feira | [Modelos Matemáticos: funções lineares]{.aula-celula .is-teoria} | [Modelos Matemáticos: funções lineares]{.aula-celula .is-teoria} | [Funções lineares](content/slides/modelos-matematicos/funcoes-lineares.pdf){target="_blank"} |  |
| [20]{.aula-idx .dia-mesma-atividade} | 19/05 | Terça-feira | [Modelos Matemáticos: polinômios]{.aula-celula .is-teoria} | [Modelos Matemáticos: polinômios]{.aula-celula .is-teoria} | [Polinômios](content/slides/modelos-matematicos/polinomios.pdf){target="_blank"} |  |
| [21]{.aula-idx .dia-revezamento} | 21/05 | Quinta-feira | [MMQ em funções lineares e polinomiais: qualidade do ajuste]{.aula-celula .is-teoria} | [LAB. INFO: MMQ na regressão linear simples em Python]{.aula-celula .is-pratica} | [Funções lineares](content/slides/modelos-matematicos/funcoes-lineares.pdf){target="_blank"}<br>[Polinômios](content/slides/modelos-matematicos/polinomios.pdf){target="_blank"} | [MMQ na regressão linear simples - Python](https://fcopf.github.io/mead/content/regressao-linear/mmq-regressao-linear-simples.html){target="_blank"} |
| [22]{.aula-idx .dia-revezamento} | 26/05 | Terça-feira | [LAB. INFO: MMQ na regressão linear simples em Python]{.aula-celula .is-pratica} | [MMQ em funções lineares e polinomiais: qualidade do ajuste]{.aula-celula .is-teoria} | [Funções lineares](content/slides/modelos-matematicos/funcoes-lineares.pdf){target="_blank"}<br>[Polinômios](content/slides/modelos-matematicos/polinomios.pdf){target="_blank"} | [MMQ na regressão linear simples - Python](https://fcopf.github.io/mead/content/regressao-linear/mmq-regressao-linear-simples.html){target="_blank"} |
| [23]{.aula-idx .dia-revezamento} | 28/05 | Quinta-feira | [MMQ em funções lineares e polinomiais: qualidade do ajuste]{.aula-celula .is-teoria} | [LAB. INFO: MMQ na regressão polinomial em Python]{.aula-celula .is-pratica} | [Funções lineares](content/slides/modelos-matematicos/funcoes-lineares.pdf){target="_blank"}<br>[Polinômios](content/slides/modelos-matematicos/polinomios.pdf){target="_blank"} | [MMQ na regressão polinomial - Python](https://fcopf.github.io/mead/content/regressao-linear/mmq-regressao-polinomial.html){target="_blank"} |
| [24]{.aula-idx .dia-revezamento} | 02/06 | Terça-feira | [LAB. INFO: MMQ na regressão polinomial em Python]{.aula-celula .is-pratica} | [MMQ em funções lineares e polinomiais: qualidade do ajuste]{.aula-celula .is-teoria} | [Funções lineares](content/slides/modelos-matematicos/funcoes-lineares.pdf){target="_blank"}<br>[Polinômios](content/slides/modelos-matematicos/polinomios.pdf){target="_blank"} | [MMQ na regressão polinomial - Python](https://fcopf.github.io/mead/content/regressao-linear/mmq-regressao-polinomial.html){target="_blank"} |
|  | 04/06 | Quinta-feira | [Feriado (Corpus Christi)]{.aula-celula .is-teoria} |  |  |  |
| [25]{.aula-idx .dia-mesma-atividade} | 09/06 | Terça-feira | [**Prova 3**]{.aula-celula .is-teoria} | [**Prova 3**]{.aula-celula .is-teoria} |  |  |
| [26]{.aula-idx .dia-mesma-atividade} | 11/06 | Quinta-feira | [Modelos Matemáticos: funções potências e exponenciais]{.aula-celula .is-teoria} | [Modelos Matemáticos: funções potências e exponenciais]{.aula-celula .is-teoria} | [Funções potências](content/slides/modelos-matematicos/funcoes-potencias.pdf){target="_blank"}<br>[Funções exponenciais e logarítmicas](content/slides/modelos-matematicos/funcoes-exponenciais-e-logaritmicas.pdf){target="_blank"} |  |
| [27]{.aula-idx .dia-mesma-atividade} | 16/06 | Terça-feira | [Modelos Matemáticos: funções logarítmicas]{.aula-celula .is-teoria} | [Modelos Matemáticos: funções logarítmicas]{.aula-celula .is-teoria} | [Funções exponenciais e logarítmicas](content/slides/modelos-matematicos/funcoes-exponenciais-e-logaritmicas.pdf){target="_blank"} |  |
| [28]{.aula-idx .dia-mesma-atividade} | 18/06 | Quinta-feira | [MMQ em funções potência, exponenciais e logarítmicas]{.aula-celula .is-teoria} | [MMQ em funções potência, exponenciais e logarítmicas]{.aula-celula .is-teoria} | [Funções potências](content/slides/modelos-matematicos/funcoes-potencias.pdf){target="_blank"}<br>[Funções exponenciais e logarítmicas](content/slides/modelos-matematicos/funcoes-exponenciais-e-logaritmicas.pdf){target="_blank"} |  |
| [29]{.aula-idx .dia-revezamento} | 23/06 | Terça-feira | [Modelos Matemáticos: funções trigonométricas]{.aula-celula .is-teoria} | [LAB. INFO: MMQ em funções potência, exponenciais e logarítmicas em Python]{.aula-celula .is-pratica} | [Funções trigonométricas](content/slides/modelos-matematicos/funcoes-trigonometricas.pdf){target="_blank"}<br>[Funções potências](content/slides/modelos-matematicos/funcoes-potencias.pdf){target="_blank"}<br>[Funções exponenciais e logarítmicas](content/slides/modelos-matematicos/funcoes-exponenciais-e-logaritmicas.pdf){target="_blank"} | [Funções potência - Python](https://fcopf.github.io/mead/content/funcoes-modelos/funcoes-potencia.html){target="_blank"} |
| [30]{.aula-idx .dia-revezamento} | 25/06 | Quinta-feira | [LAB. INFO: MMQ em funções potência, exponenciais e logarítmicas em Python]{.aula-celula .is-pratica} | [Modelos Matemáticos: funções trigonométricas]{.aula-celula .is-teoria} | [Funções trigonométricas](content/slides/modelos-matematicos/funcoes-trigonometricas.pdf){target="_blank"}<br>[Funções potências](content/slides/modelos-matematicos/funcoes-potencias.pdf){target="_blank"}<br>[Funções exponenciais e logarítmicas](content/slides/modelos-matematicos/funcoes-exponenciais-e-logaritmicas.pdf){target="_blank"} | [Funções potência - Python](https://fcopf.github.io/mead/content/funcoes-modelos/funcoes-potencia.html){target="_blank"} |
| [31]{.aula-idx .dia-revezamento} | 30/06 | Terça-feira | [Modelos Matemáticos: funções trigonométricas]{.aula-celula .is-teoria} | [LAB. INFO: MMQ em funções trigonométricas em Python]{.aula-celula .is-pratica} | [Funções trigonométricas](content/slides/modelos-matematicos/funcoes-trigonometricas.pdf){target="_blank"} |  |
| [32]{.aula-idx .dia-revezamento} | 02/07 | Quinta-feira | [LAB. INFO: MMQ em funções trigonométricas em Python]{.aula-celula .is-pratica} | [Modelos Matemáticos: funções trigonométricas]{.aula-celula .is-teoria} | [Funções trigonométricas](content/slides/modelos-matematicos/funcoes-trigonometricas.pdf){target="_blank"} |  |
| [33]{.aula-idx .dia-mesma-atividade} | 07/07 | Terça-feira | [**Prova 4**]{.aula-celula .is-teoria} | [**Prova 4**]{.aula-celula .is-teoria} |  |  |
|  | 09/07 | Quinta-feira | [Feriado (Revolução Constitucionalista)]{.aula-celula .is-teoria} |  |  |  |
|  | 14/07 | Terça-feira | [Exame]{.aula-celula .is-teoria} |  |  |  |
:::
