---
title: "PROVA 1"
subtitle: "Bases da Matemática e Estatística (BME) - 1º semestre de 2026"
date: 2026-04-14
date-format: "DD/MM/YYYY"
format:
  pdf:
    fontsize: 10pt
    geometry: "top=1.4cm, bottom=2.2cm, left=1.5cm, right=1.5cm"
    include-in-header:
      text: |
        \renewcommand{\maketitle}{}
        \usepackage{tabularx}
        \usepackage{multicol}
        \setlength{\columnsep}{1.5em}
        \setlength{\columnseprule}{0.4pt}

lang: pt-br
---

```{=latex}
\begin{center}
  {\large\textbf{PROVA 1}}\\[0.3em]
  {\normalsize Bases da Matemática e Estatística (BME) -- 1º semestre de 2026}\\[0.3em]
  {\normalsize 14/04/2026}
\end{center}
\vspace{0.8em}
\begin{tabularx}{\linewidth}{@{}l>{\hsize=1.5\hsize\arraybackslash}Xl>{\hsize=0.5\hsize\arraybackslash}X@{}}
\textbf{Nome:}  & \hrulefill & \textbf{RA:}    & \hrulefill \\[1.2em]
\textbf{Termo:} & \hrulefill & \textbf{Turno:} & \hrulefill \\[0.4em]
\end{tabularx}
\vspace{1em}
```

## Questões

```{=latex}
\begin{multicols}{2}
```

**1. Considere os pontos $A=(2,-1)$ e $B=(5,3)$. O vetor $\vec{AB}$ é:**

A. $(7,2)$

B. $(3,4)$

C. $(-3,4)$

D. $(4,3)$

E. $(3,-4)$

```{=latex}
\vspace{8pt}
```

**2. Se $\vec{u}=(1,-2)$ e $\vec{v}=(3,1)$, então $2\vec{u}-\vec{v}$ é igual a:**

A. $(-1,-5)$

B. $(5,-1)$

C. $(-5,-1)$

D. $(1,-5)$

E. $(-1,5)$

```{=latex}
\vspace{8pt}
```

**3. Se $\vec{u}=(2,3)$ e $\vec{v}=(-3,2)$, então o ângulo entre $\vec{u}$ e $\vec{v}$ é:**

A. $0^\circ$

B. $30^\circ$

C. $45^\circ$

D. $90^\circ$

E. $180^\circ$

```{=latex}
\vspace{8pt}

```

**4. O vetor unitário com o mesmo sentido de $\vec{v}=(3,4)$ é:**

A. $(4,3)$

B. $\left(\frac{3}{4},1\right)$

C. $\left(\frac{3}{5},\frac{4}{5}\right)$

D. $\left(\frac{1}{3},\frac{1}{4}\right)$

E. $(5,5)$

```{=latex}
\vspace{8pt}
\columnbreak
```

**5. Em um estudo, a morfometria de duas espécies são representadas pelos vetores:**  

```{=latex}
\vspace{8pt}
```

$\vec{p}=(1,2,2), \qquad \vec{q}=(2,1,2).$

```{=latex}
\vspace{8pt}
```

**Determine o $\cos(\theta)$ entre $\vec{p}$ e $\vec{q}$ é:**

A. $\frac{7}{9}$

B. $\frac{2}{3}$

C. $1$

D. $\frac{8}{9}$

E. $\frac{\sqrt{8}}{9}$

```{=latex}
\vspace{8pt}

```

**6. Considere o sistema:**
$\begin{cases}
2y+3z=8\\
2x+3y+z=5\\
x-y-2z=-5
\end{cases}$

**A solução do sistema é:**

A. $(1,0,2)$

B. $(0,2,1)$

C. $(0,1,2)$

D. $(2,1,0)$

E. $(1,1,1)$

```{=latex}
\vspace{8pt}
```

**7. Considere o sistema:**
$\begin{cases}
x-y+2z=3\\
x+2y-z=-3\\
2y-2z=1
\end{cases}$

**Esse sistema é:**

A. possível e determinado

B. equivalente ao sistema $x=y=z=0$

C. possível e indeterminado com uma variável livre

D. homogêneo

E. impossível

```{=latex}
\vspace{8pt}
\columnbreak
```

**8. Se**
$A=\begin{bmatrix}1&2\\0&1\end{bmatrix}
\quad \text{e} \quad
B=\begin{bmatrix}3&-1\\2&4\end{bmatrix},$

```{=latex}
\vspace{8pt}
```

**então $2A+B^T$ é:**

```{=latex}
\vspace{8pt}
```

A. $\begin{bmatrix}5&3\\2&6\end{bmatrix}$

B. $\begin{bmatrix}5&6\\-1&6\end{bmatrix}$

C. $\begin{bmatrix}2&4\\0&2\end{bmatrix}$

D. $\begin{bmatrix}5&-1\\6&6\end{bmatrix}$

E. $\begin{bmatrix}3&2\\-1&4\end{bmatrix}$

```{=latex}
\vspace{8pt}

```

**9. Se**
$A=\begin{bmatrix}1&2\\0&1\end{bmatrix}
\quad \text{e} \quad
B=\begin{bmatrix}3&-1\\2&4\end{bmatrix},$

```{=latex}
\vspace{8pt}
```

**então o produto $AB$ é:**

```{=latex}
\vspace{8pt}
```

A. $\begin{bmatrix}3&7\\2&4\end{bmatrix}$

B. $\begin{bmatrix}7&7\\2&4\end{bmatrix}$

C. $\begin{bmatrix}5&3\\2&4\end{bmatrix}$

D. $\begin{bmatrix}7&2\\7&4\end{bmatrix}$

E. $\begin{bmatrix}1&2\\3&4\end{bmatrix}$

```{=latex}
\vspace{8pt}
\columnbreak
```

**10. A inversa da matriz $A=\begin{bmatrix}2&5\\1&3\end{bmatrix}$ é:**

A. $\begin{bmatrix}3&5\\1&2\end{bmatrix}$

B. $\begin{bmatrix}2&-5\\-1&3\end{bmatrix}$

C. $\begin{bmatrix}3&-1\\-5&2\end{bmatrix}$

D. $\begin{bmatrix}-3&5\\1&-2\end{bmatrix}$

E. $\begin{bmatrix}3&-5\\-1&2\end{bmatrix}$

```{=latex}
\end{multicols}
```
