---
title: "PROVA 2"
subtitle: "Bases da Matemática e Estatística (BME) - 1º semestre de 2026"
date: 2026-05-12
date-format: "DD/MM/YYYY"
format:
  pdf:
    fontsize: 10pt
    geometry: "top=1.4cm, bottom=2.2cm, left=1.5cm, right=1.5cm"
    include-in-header:
      text: |
        \renewcommand{\maketitle}{}
        \usepackage{tabularx}
        \usepackage{multicol}
        \setlength{\columnsep}{1.5em}
        \setlength{\columnseprule}{0.4pt}

lang: pt-br
---

```{=latex}
\begin{center}
  {\large\textbf{PROVA 2}}\\[0.3em]
  {\normalsize Bases da Matemática e Estatística (BME) -- 1º semestre de 2026}\\[0.3em]
  {\normalsize 12/05/2026}
\end{center}
\vspace{0.8em}
\begin{tabularx}{\linewidth}{@{}l>{\hsize=1.5\hsize\arraybackslash}Xl>{\hsize=0.5\hsize\arraybackslash}X@{}}
\textbf{Nome:}  & \hrulefill & \textbf{RA:}    & \hrulefill \\[1.2em]
\textbf{Termo:} & \hrulefill & \textbf{Turno:} & \hrulefill \\[0.4em]
\end{tabularx}
\vspace{1em}
```

## Questões 

```{=latex}
\begin{multicols}{2}
```

**1. No Método dos Mínimos Quadrados (MMQ), a reta $\hat{y} = \beta_0 + \beta_1 y$ é ajustada de modo a minimizar:**

A. $\sum_{i=1}^n e_i$

B. $\sum_{i=1}^n |e_i|$

C. $\sum_{i=1}^n y_i^2$

D. A correlação entre $x$ e $y$

E. $\sum_{i=1}^n e_i^2$

```{=latex}
\vspace{8pt} 
```


**2. No MMQ, os resíduos são definidos por $e_i = y_i - \hat{y}_i$. Considere as variáveis $x = (1,\, 2,\, 3,\, 4,\, 5)$ e $y = (3,\, 4,\, 6,\, 5,\, 7)$. A reta ajustada para estes pares de observações é dada por $\hat{y} = \beta_0 + \beta_1\, x$, sendo $\beta_0 = 2$ e $\beta_1 = 1$. Qual é o valor de $SQ_{res}$?**

A. 0

B. 1

C. 2

D. 4

E. 8

```{=latex}
\vspace{8pt}
```

**3. A solução de mínimos quadrados é dada por $B = (X^T X)^{-1}(X^T Y)$, onde $X$ é uma matriz $n \times 2$ cuja primeira coluna é formada por 1s e a segunda coluna pelos valores de $x$. Considere as variáveis $x = (1,\,2,\,3,\,4,\,5)$ e $y = (3,\,5,\,7,\,9,\,11)$. Qual é o valor do vetor $X^T Y$?**

A. $\begin{bmatrix} 35 \\ 125 \end{bmatrix}$

B. $\begin{bmatrix} 15 \\ 125 \end{bmatrix}$

C. $\begin{bmatrix} 35 \\ 55 \end{bmatrix}$

D. $\begin{bmatrix} 125 \\ 35 \end{bmatrix}$

E. $\begin{bmatrix} 15 \\ 55 \end{bmatrix}$

```{=latex}
\vspace{8pt}
```

**4. Em um experimento com $n = 5$ pares $(x_i, y_i)$, obteve-se $\bar{x} = 3$, $\bar{y} = 7$, $\sum (x_i - \bar{x})^2 = 10$ e $\sum (x_i - \bar{x})(y_i - \bar{y}) = 15$. O coeficiente $\beta_1$ da reta de regressão linear simples é:**

A. 0,5

B. 1,5

C. 1,0

D. 2,0

E. 3,0

```{=latex}
\vspace{8pt}
```

**5. As concentrações de clorofila (em μg/L) medidas em 5 amostras de água foram 10, 12, 8, 14 e 11. A média aritmética dessas concentrações é:**

A. 10,0

B. 11,0

C. 10,5

D. 12,0

E. 11,5

```{=latex}
\vspace{8pt}
\columnbreak
```

**6. Seja $\bar{x}$ a média aritmética de $x_1, x_2, \ldots, x_n$. Qual das afirmações abaixo é correta?**

A. $\sum_{i=1}^n (x_i - \bar{x}) = n$

B. $\bar{x}$ é o valor que maximiza $\sum_{i=1}^n (x_i - c)^2$

C. $\bar{x}$ é sempre maior do que qualquer desvio individual $d_i = x_i - \bar{x}$

D. $\sum_{i=1}^n (x_i - \bar{x}) = 0$

E. A média aritmética só está definida quando todos os valores são positivos

```{=latex}
\vspace{8pt}
```

**7. Para o conjunto $x = \{2,\, 4,\, 4,\, 6,\, 4\}$, a variância amostral $s^2$ é:**

A. 2,0

B. 1,6

C. 2,5

D. 4,0

E. 8,0

```{=latex}
\vspace{8pt}
```

**8. Considere os vetores de observações $x = (1,\, 3,\, 5)$ e $y = (2,\, 4,\, 6)$. A covariância amostral $s_{xy}$ entre $x$ e $y$ é:**


A. 1

B. 2

C. 6

D. 8

E. 4

```{=latex}
\vspace{8pt}
\columnbreak
```

**9. Em um ajuste de regressão linear simples com $n = 20$ observações, obteve-se $SQ_{Total} = 120$ e $SQ_{Res} = 30$. Analise as afirmações:**

**I.** $SQ_{Reg} = 90$

**II.** $R^2 = 0{,}75$

**III.** O modelo explica $75\%$ da variação total de $y$ em torno de sua média.

**Estão corretas:**

A. Apenas I e III

B. Apenas I

C. I, II e III

D. Apenas II

E. Apenas II e III

```{=latex}
\vspace{8pt}
```

**10. Para os pares $(x_i,\, y_i)$ com $x = (1,\, 2,\, 3,\, 4,\, 5)$ e $y = (1,\, 3,\, 2,\, 5,\, 4)$, o coeficiente de determinação $R^2$ da regressão linear simples de $y$ em $x$ é:**

A. 0,64

B. 0,80

C. 0,50

D. 0,40

E. 0,72

```{=latex}
\end{multicols}
```
